version: "3"
services:
  web:
    build: .
    links:
      - database
    ports:
      - 8080:8080
    command: sh -c "npm install && npm run dev"
    volumes:
      - ".:/app"
    environment:
      HOST: 0.0.0.0


  database:
    build:
      context: ./api/docker/database
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ./api/docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./api/docker/database/data:/var/lib/mysql

  php-fpm:
    build:
      context: ./api/docker/php-fpm
    depends_on:
      - database
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=5.7
    volumes:
      - ./api/src:/var/www

  nginx:
    build:
      context: ./api/docker/nginx
    volumes:
      - ./api/src:/var/www
      - ./api/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./api/docker/nginx/sites/:/etc/nginx/sites-available
      - ./api/docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./api/docker/logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"

